export const mapConfig = {
  seed: "seed",
  scale: 200,
  rows: 100,
  cols: 100,
  waterHeight: 50,
  hexRadius: 3,
  frequency: 0.4,
  amplitude: 0.8,
  maxAmplitude: 0,
  persistence: 0.5,
  lacunarity: 2,
  octaves: 3,
  groupNuageCount: 10,
  NuagePerGroup: 10,
  weatherMode: "clear",
  sunRotationSpeed: 0,
};
